name: cornerstone_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:

  http: ^1.5.0
  animations: ^2.1.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  supabase_flutter: ^2.10.3
  logger: ^2.6.2
  url_launcher: ^6.3.2
  riverpod: ^3.0.3
  flutter_riverpod: ^3.0.3
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  path: ^1.9.1
  video_player: ^2.10.1
  audioplayers: ^6.5.1
  file_picker: ^10.3.6
  pdf: ^3.11.3
  share_plus: ^12.0.1
  epub_plus: ^5.1.0
  universal_html: ^2.3.0
  web: ^1.1.1

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# App icon configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app_icon.jpg"

  web:
    generate: true
    image_path: "assets/icon/app_icon.jpg"
    background_color: "#ffffff"
    theme_color: "#ffffff"

  windows:
    generate: true
    image_path: "assets/icon/app_icon.jpg"
    icon_size: 48

  macos:
    generate: true
    image_path: "assets/icon/app_icon.jpg"

# App name configuration (optional)
flutter_launcher_name:
  name: "Cornerstone Hub"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.jpg
    - assets/images/page.png
    - assets/images/cornerstone_logo.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400